namespace GlumSak_PasteCreator
{
    partial class MainWindow
    {
        /// <summary>
        /// Erforderliche Designervariable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Verwendete Ressourcen bereinigen.
        /// </summary>
        /// <param name="disposing">True, wenn verwaltete Ressourcen gelöscht werden sollen; andernfalls False.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Vom Windows Form-Designer generierter Code

        /// <summary>
        /// Erforderliche Methode für die Designerunterstützung.
        /// Der Inhalt der Methode darf nicht mit dem Code-Editor geändert werden.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MainWindow));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.bunifuSeparator1 = new Bunifu.UI.WinForms.BunifuSeparator();
            this.Items_label = new Bunifu.UI.WinForms.BunifuLabel();
            this.Links_label = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuSeparator2 = new Bunifu.UI.WinForms.BunifuSeparator();
            this.bunifuSeparator3 = new Bunifu.UI.WinForms.BunifuSeparator();
            this.Items_ListBox = new System.Windows.Forms.ListBox();
            this.Links_ListBox = new System.Windows.Forms.ListBox();
            this.Item_TextBox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.Link_TextBox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.AddLink_Button = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.AddItem_Button = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.ItemsRemove_Button = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.LinksRemove_Button = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.LinksClear_Button = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.ItemsClear_Button = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.SuspendLayout();
            // 
            // bunifuSeparator1
            // 
            this.bunifuSeparator1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuSeparator1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuSeparator1.BackgroundImage")));
            this.bunifuSeparator1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuSeparator1.DashCap = Bunifu.UI.WinForms.BunifuSeparator.CapStyles.Flat;
            this.bunifuSeparator1.LineColor = System.Drawing.Color.Silver;
            this.bunifuSeparator1.LineStyle = Bunifu.UI.WinForms.BunifuSeparator.LineStyles.Solid;
            this.bunifuSeparator1.LineThickness = 1;
            this.bunifuSeparator1.Location = new System.Drawing.Point(418, 11);
            this.bunifuSeparator1.Name = "bunifuSeparator1";
            this.bunifuSeparator1.Orientation = Bunifu.UI.WinForms.BunifuSeparator.LineOrientation.Vertical;
            this.bunifuSeparator1.Size = new System.Drawing.Size(14, 612);
            this.bunifuSeparator1.TabIndex = 0;
            // 
            // Items_label
            // 
            this.Items_label.AllowParentOverrides = false;
            this.Items_label.AutoEllipsis = false;
            this.Items_label.Cursor = System.Windows.Forms.Cursors.Default;
            this.Items_label.CursorType = System.Windows.Forms.Cursors.Default;
            this.Items_label.Font = new System.Drawing.Font("Segoe UI", 13F);
            this.Items_label.Location = new System.Drawing.Point(12, 9);
            this.Items_label.Name = "Items_label";
            this.Items_label.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.Items_label.Size = new System.Drawing.Size(42, 23);
            this.Items_label.TabIndex = 1;
            this.Items_label.Text = "Items";
            this.Items_label.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.Items_label.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // Links_label
            // 
            this.Links_label.AllowParentOverrides = false;
            this.Links_label.AutoEllipsis = false;
            this.Links_label.CursorType = null;
            this.Links_label.Font = new System.Drawing.Font("Segoe UI", 13F);
            this.Links_label.Location = new System.Drawing.Point(438, 9);
            this.Links_label.Name = "Links_label";
            this.Links_label.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.Links_label.Size = new System.Drawing.Size(37, 23);
            this.Links_label.TabIndex = 2;
            this.Links_label.Text = "Links";
            this.Links_label.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.Links_label.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuSeparator2
            // 
            this.bunifuSeparator2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuSeparator2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuSeparator2.BackgroundImage")));
            this.bunifuSeparator2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuSeparator2.DashCap = Bunifu.UI.WinForms.BunifuSeparator.CapStyles.Flat;
            this.bunifuSeparator2.LineColor = System.Drawing.Color.Silver;
            this.bunifuSeparator2.LineStyle = Bunifu.UI.WinForms.BunifuSeparator.LineStyles.Solid;
            this.bunifuSeparator2.LineThickness = 1;
            this.bunifuSeparator2.Location = new System.Drawing.Point(12, 38);
            this.bunifuSeparator2.Name = "bunifuSeparator2";
            this.bunifuSeparator2.Orientation = Bunifu.UI.WinForms.BunifuSeparator.LineOrientation.Horizontal;
            this.bunifuSeparator2.Size = new System.Drawing.Size(400, 14);
            this.bunifuSeparator2.TabIndex = 3;
            // 
            // bunifuSeparator3
            // 
            this.bunifuSeparator3.BackColor = System.Drawing.Color.Transparent;
            this.bunifuSeparator3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuSeparator3.BackgroundImage")));
            this.bunifuSeparator3.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuSeparator3.DashCap = Bunifu.UI.WinForms.BunifuSeparator.CapStyles.Flat;
            this.bunifuSeparator3.LineColor = System.Drawing.Color.Silver;
            this.bunifuSeparator3.LineStyle = Bunifu.UI.WinForms.BunifuSeparator.LineStyles.Solid;
            this.bunifuSeparator3.LineThickness = 1;
            this.bunifuSeparator3.Location = new System.Drawing.Point(438, 38);
            this.bunifuSeparator3.Name = "bunifuSeparator3";
            this.bunifuSeparator3.Orientation = Bunifu.UI.WinForms.BunifuSeparator.LineOrientation.Horizontal;
            this.bunifuSeparator3.Size = new System.Drawing.Size(400, 14);
            this.bunifuSeparator3.TabIndex = 4;
            // 
            // Items_ListBox
            // 
            this.Items_ListBox.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.Items_ListBox.FormattingEnabled = true;
            this.Items_ListBox.HorizontalScrollbar = true;
            this.Items_ListBox.Location = new System.Drawing.Point(12, 201);
            this.Items_ListBox.Name = "Items_ListBox";
            this.Items_ListBox.Size = new System.Drawing.Size(400, 433);
            this.Items_ListBox.TabIndex = 5;
            this.Items_ListBox.KeyDown += new System.Windows.Forms.KeyEventHandler(this.Items_ListBox_KeyDown);
            this.Items_ListBox.MouseDoubleClick += new System.Windows.Forms.MouseEventHandler(this.Items_ListBox_MouseDoubleClick);
            // 
            // Links_ListBox
            // 
            this.Links_ListBox.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.Links_ListBox.FormattingEnabled = true;
            this.Links_ListBox.HorizontalScrollbar = true;
            this.Links_ListBox.Location = new System.Drawing.Point(438, 201);
            this.Links_ListBox.Name = "Links_ListBox";
            this.Links_ListBox.Size = new System.Drawing.Size(400, 433);
            this.Links_ListBox.TabIndex = 6;
            this.Links_ListBox.KeyDown += new System.Windows.Forms.KeyEventHandler(this.Links_ListBox_KeyDown);
            this.Links_ListBox.MouseDoubleClick += new System.Windows.Forms.MouseEventHandler(this.Links_ListBox_MouseDoubleClick);
            // 
            // Item_TextBox
            // 
            this.Item_TextBox.AcceptsReturn = false;
            this.Item_TextBox.AcceptsTab = false;
            this.Item_TextBox.AnimationSpeed = 200;
            this.Item_TextBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.Item_TextBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.Item_TextBox.BackColor = System.Drawing.Color.Transparent;
            this.Item_TextBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Item_TextBox.BackgroundImage")));
            this.Item_TextBox.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.Item_TextBox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Item_TextBox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Item_TextBox.BorderColorIdle = System.Drawing.Color.Silver;
            this.Item_TextBox.BorderRadius = 1;
            this.Item_TextBox.BorderThickness = 1;
            this.Item_TextBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.Item_TextBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.Item_TextBox.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.Item_TextBox.DefaultText = "";
            this.Item_TextBox.FillColor = System.Drawing.Color.White;
            this.Item_TextBox.HideSelection = true;
            this.Item_TextBox.IconLeft = null;
            this.Item_TextBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.Item_TextBox.IconPadding = 10;
            this.Item_TextBox.IconRight = null;
            this.Item_TextBox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.Item_TextBox.Lines = new string[0];
            this.Item_TextBox.Location = new System.Drawing.Point(12, 58);
            this.Item_TextBox.MaxLength = 32767;
            this.Item_TextBox.MinimumSize = new System.Drawing.Size(1, 1);
            this.Item_TextBox.Modified = false;
            this.Item_TextBox.Multiline = false;
            this.Item_TextBox.Name = "Item_TextBox";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Item_TextBox.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.Item_TextBox.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Item_TextBox.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Item_TextBox.OnIdleState = stateProperties4;
            this.Item_TextBox.Padding = new System.Windows.Forms.Padding(3);
            this.Item_TextBox.PasswordChar = '\0';
            this.Item_TextBox.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.Item_TextBox.PlaceholderText = "Enter item";
            this.Item_TextBox.ReadOnly = false;
            this.Item_TextBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.Item_TextBox.SelectedText = "";
            this.Item_TextBox.SelectionLength = 0;
            this.Item_TextBox.SelectionStart = 0;
            this.Item_TextBox.ShortcutsEnabled = true;
            this.Item_TextBox.Size = new System.Drawing.Size(323, 37);
            this.Item_TextBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.Item_TextBox.TabIndex = 7;
            this.Item_TextBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.Item_TextBox.TextMarginBottom = 0;
            this.Item_TextBox.TextMarginLeft = 3;
            this.Item_TextBox.TextMarginTop = 0;
            this.Item_TextBox.TextPlaceholder = "Enter item";
            this.Item_TextBox.UseSystemPasswordChar = false;
            this.Item_TextBox.WordWrap = true;
            // 
            // Link_TextBox
            // 
            this.Link_TextBox.AcceptsReturn = false;
            this.Link_TextBox.AcceptsTab = false;
            this.Link_TextBox.AnimationSpeed = 200;
            this.Link_TextBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.Link_TextBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.Link_TextBox.BackColor = System.Drawing.Color.Transparent;
            this.Link_TextBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Link_TextBox.BackgroundImage")));
            this.Link_TextBox.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.Link_TextBox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Link_TextBox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Link_TextBox.BorderColorIdle = System.Drawing.Color.Silver;
            this.Link_TextBox.BorderRadius = 1;
            this.Link_TextBox.BorderThickness = 1;
            this.Link_TextBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.Link_TextBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.Link_TextBox.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.Link_TextBox.DefaultText = "";
            this.Link_TextBox.FillColor = System.Drawing.Color.White;
            this.Link_TextBox.HideSelection = true;
            this.Link_TextBox.IconLeft = null;
            this.Link_TextBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.Link_TextBox.IconPadding = 10;
            this.Link_TextBox.IconRight = null;
            this.Link_TextBox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.Link_TextBox.Lines = new string[0];
            this.Link_TextBox.Location = new System.Drawing.Point(438, 58);
            this.Link_TextBox.MaxLength = 32767;
            this.Link_TextBox.MinimumSize = new System.Drawing.Size(1, 1);
            this.Link_TextBox.Modified = false;
            this.Link_TextBox.Multiline = false;
            this.Link_TextBox.Name = "Link_TextBox";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Link_TextBox.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.Link_TextBox.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Link_TextBox.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Link_TextBox.OnIdleState = stateProperties8;
            this.Link_TextBox.Padding = new System.Windows.Forms.Padding(3);
            this.Link_TextBox.PasswordChar = '\0';
            this.Link_TextBox.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.Link_TextBox.PlaceholderText = "Enter DDL link";
            this.Link_TextBox.ReadOnly = false;
            this.Link_TextBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.Link_TextBox.SelectedText = "";
            this.Link_TextBox.SelectionLength = 0;
            this.Link_TextBox.SelectionStart = 0;
            this.Link_TextBox.ShortcutsEnabled = true;
            this.Link_TextBox.Size = new System.Drawing.Size(325, 37);
            this.Link_TextBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.Link_TextBox.TabIndex = 8;
            this.Link_TextBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.Link_TextBox.TextMarginBottom = 0;
            this.Link_TextBox.TextMarginLeft = 3;
            this.Link_TextBox.TextMarginTop = 0;
            this.Link_TextBox.TextPlaceholder = "Enter DDL link";
            this.Link_TextBox.UseSystemPasswordChar = false;
            this.Link_TextBox.WordWrap = true;
            // 
            // AddLink_Button
            // 
            this.AddLink_Button.AllowAnimations = true;
            this.AddLink_Button.AllowMouseEffects = true;
            this.AddLink_Button.AllowToggling = false;
            this.AddLink_Button.AnimationSpeed = 200;
            this.AddLink_Button.AutoGenerateColors = false;
            this.AddLink_Button.AutoRoundBorders = false;
            this.AddLink_Button.AutoSizeLeftIcon = true;
            this.AddLink_Button.AutoSizeRightIcon = true;
            this.AddLink_Button.BackColor = System.Drawing.Color.Transparent;
            this.AddLink_Button.BackColor1 = System.Drawing.Color.Silver;
            this.AddLink_Button.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AddLink_Button.BackgroundImage")));
            this.AddLink_Button.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AddLink_Button.ButtonText = "Add";
            this.AddLink_Button.ButtonTextMarginLeft = 0;
            this.AddLink_Button.ColorContrastOnClick = 45;
            this.AddLink_Button.ColorContrastOnHover = 45;
            this.AddLink_Button.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.AddLink_Button.CustomizableEdges = borderEdges1;
            this.AddLink_Button.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AddLink_Button.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AddLink_Button.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AddLink_Button.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AddLink_Button.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AddLink_Button.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.AddLink_Button.ForeColor = System.Drawing.Color.White;
            this.AddLink_Button.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AddLink_Button.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AddLink_Button.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.AddLink_Button.IconMarginLeft = 11;
            this.AddLink_Button.IconPadding = 10;
            this.AddLink_Button.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AddLink_Button.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AddLink_Button.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.AddLink_Button.IconSize = 25;
            this.AddLink_Button.IdleBorderColor = System.Drawing.Color.Silver;
            this.AddLink_Button.IdleBorderRadius = 1;
            this.AddLink_Button.IdleBorderThickness = 1;
            this.AddLink_Button.IdleFillColor = System.Drawing.Color.Silver;
            this.AddLink_Button.IdleIconLeftImage = null;
            this.AddLink_Button.IdleIconRightImage = null;
            this.AddLink_Button.IndicateFocus = false;
            this.AddLink_Button.Location = new System.Drawing.Point(769, 58);
            this.AddLink_Button.Name = "AddLink_Button";
            this.AddLink_Button.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AddLink_Button.OnDisabledState.BorderRadius = 1;
            this.AddLink_Button.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AddLink_Button.OnDisabledState.BorderThickness = 1;
            this.AddLink_Button.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AddLink_Button.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AddLink_Button.OnDisabledState.IconLeftImage = null;
            this.AddLink_Button.OnDisabledState.IconRightImage = null;
            this.AddLink_Button.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.AddLink_Button.onHoverState.BorderRadius = 1;
            this.AddLink_Button.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AddLink_Button.onHoverState.BorderThickness = 1;
            this.AddLink_Button.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.AddLink_Button.onHoverState.ForeColor = System.Drawing.Color.White;
            this.AddLink_Button.onHoverState.IconLeftImage = null;
            this.AddLink_Button.onHoverState.IconRightImage = null;
            this.AddLink_Button.OnIdleState.BorderColor = System.Drawing.Color.Silver;
            this.AddLink_Button.OnIdleState.BorderRadius = 1;
            this.AddLink_Button.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AddLink_Button.OnIdleState.BorderThickness = 1;
            this.AddLink_Button.OnIdleState.FillColor = System.Drawing.Color.Silver;
            this.AddLink_Button.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.AddLink_Button.OnIdleState.IconLeftImage = null;
            this.AddLink_Button.OnIdleState.IconRightImage = null;
            this.AddLink_Button.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.AddLink_Button.OnPressedState.BorderRadius = 1;
            this.AddLink_Button.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AddLink_Button.OnPressedState.BorderThickness = 1;
            this.AddLink_Button.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.AddLink_Button.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.AddLink_Button.OnPressedState.IconLeftImage = null;
            this.AddLink_Button.OnPressedState.IconRightImage = null;
            this.AddLink_Button.Size = new System.Drawing.Size(69, 37);
            this.AddLink_Button.TabIndex = 9;
            this.AddLink_Button.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AddLink_Button.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AddLink_Button.TextMarginLeft = 0;
            this.AddLink_Button.TextPadding = new System.Windows.Forms.Padding(0);
            this.AddLink_Button.UseDefaultRadiusAndThickness = true;
            this.AddLink_Button.Click += new System.EventHandler(this.AddLink_Button_Click);
            // 
            // AddItem_Button
            // 
            this.AddItem_Button.AllowAnimations = true;
            this.AddItem_Button.AllowMouseEffects = true;
            this.AddItem_Button.AllowToggling = false;
            this.AddItem_Button.AnimationSpeed = 200;
            this.AddItem_Button.AutoGenerateColors = false;
            this.AddItem_Button.AutoRoundBorders = false;
            this.AddItem_Button.AutoSizeLeftIcon = true;
            this.AddItem_Button.AutoSizeRightIcon = true;
            this.AddItem_Button.BackColor = System.Drawing.Color.Transparent;
            this.AddItem_Button.BackColor1 = System.Drawing.Color.Silver;
            this.AddItem_Button.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AddItem_Button.BackgroundImage")));
            this.AddItem_Button.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AddItem_Button.ButtonText = "Add";
            this.AddItem_Button.ButtonTextMarginLeft = 0;
            this.AddItem_Button.ColorContrastOnClick = 45;
            this.AddItem_Button.ColorContrastOnHover = 45;
            this.AddItem_Button.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.AddItem_Button.CustomizableEdges = borderEdges2;
            this.AddItem_Button.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AddItem_Button.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AddItem_Button.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AddItem_Button.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AddItem_Button.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AddItem_Button.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.AddItem_Button.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.AddItem_Button.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AddItem_Button.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AddItem_Button.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.AddItem_Button.IconMarginLeft = 11;
            this.AddItem_Button.IconPadding = 10;
            this.AddItem_Button.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AddItem_Button.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AddItem_Button.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.AddItem_Button.IconSize = 25;
            this.AddItem_Button.IdleBorderColor = System.Drawing.Color.Silver;
            this.AddItem_Button.IdleBorderRadius = 1;
            this.AddItem_Button.IdleBorderThickness = 1;
            this.AddItem_Button.IdleFillColor = System.Drawing.Color.Silver;
            this.AddItem_Button.IdleIconLeftImage = null;
            this.AddItem_Button.IdleIconRightImage = null;
            this.AddItem_Button.IndicateFocus = false;
            this.AddItem_Button.Location = new System.Drawing.Point(341, 58);
            this.AddItem_Button.Name = "AddItem_Button";
            this.AddItem_Button.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AddItem_Button.OnDisabledState.BorderRadius = 1;
            this.AddItem_Button.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AddItem_Button.OnDisabledState.BorderThickness = 1;
            this.AddItem_Button.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AddItem_Button.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AddItem_Button.OnDisabledState.IconLeftImage = null;
            this.AddItem_Button.OnDisabledState.IconRightImage = null;
            this.AddItem_Button.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.AddItem_Button.onHoverState.BorderRadius = 1;
            this.AddItem_Button.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AddItem_Button.onHoverState.BorderThickness = 1;
            this.AddItem_Button.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.AddItem_Button.onHoverState.ForeColor = System.Drawing.Color.White;
            this.AddItem_Button.onHoverState.IconLeftImage = null;
            this.AddItem_Button.onHoverState.IconRightImage = null;
            this.AddItem_Button.OnIdleState.BorderColor = System.Drawing.Color.Silver;
            this.AddItem_Button.OnIdleState.BorderRadius = 1;
            this.AddItem_Button.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AddItem_Button.OnIdleState.BorderThickness = 1;
            this.AddItem_Button.OnIdleState.FillColor = System.Drawing.Color.Silver;
            this.AddItem_Button.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.AddItem_Button.OnIdleState.IconLeftImage = null;
            this.AddItem_Button.OnIdleState.IconRightImage = null;
            this.AddItem_Button.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.AddItem_Button.OnPressedState.BorderRadius = 1;
            this.AddItem_Button.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AddItem_Button.OnPressedState.BorderThickness = 1;
            this.AddItem_Button.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.AddItem_Button.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.AddItem_Button.OnPressedState.IconLeftImage = null;
            this.AddItem_Button.OnPressedState.IconRightImage = null;
            this.AddItem_Button.Size = new System.Drawing.Size(71, 37);
            this.AddItem_Button.TabIndex = 10;
            this.AddItem_Button.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AddItem_Button.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AddItem_Button.TextMarginLeft = 0;
            this.AddItem_Button.TextPadding = new System.Windows.Forms.Padding(0);
            this.AddItem_Button.UseDefaultRadiusAndThickness = true;
            this.AddItem_Button.Click += new System.EventHandler(this.AddItem_Button_Click);
            // 
            // ItemsRemove_Button
            // 
            this.ItemsRemove_Button.AllowAnimations = true;
            this.ItemsRemove_Button.AllowMouseEffects = true;
            this.ItemsRemove_Button.AllowToggling = false;
            this.ItemsRemove_Button.AnimationSpeed = 200;
            this.ItemsRemove_Button.AutoGenerateColors = false;
            this.ItemsRemove_Button.AutoRoundBorders = false;
            this.ItemsRemove_Button.AutoSizeLeftIcon = true;
            this.ItemsRemove_Button.AutoSizeRightIcon = true;
            this.ItemsRemove_Button.BackColor = System.Drawing.Color.Transparent;
            this.ItemsRemove_Button.BackColor1 = System.Drawing.Color.Silver;
            this.ItemsRemove_Button.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ItemsRemove_Button.BackgroundImage")));
            this.ItemsRemove_Button.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ItemsRemove_Button.ButtonText = "Remove selected";
            this.ItemsRemove_Button.ButtonTextMarginLeft = 0;
            this.ItemsRemove_Button.ColorContrastOnClick = 45;
            this.ItemsRemove_Button.ColorContrastOnHover = 45;
            this.ItemsRemove_Button.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.ItemsRemove_Button.CustomizableEdges = borderEdges3;
            this.ItemsRemove_Button.DialogResult = System.Windows.Forms.DialogResult.None;
            this.ItemsRemove_Button.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.ItemsRemove_Button.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ItemsRemove_Button.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.ItemsRemove_Button.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.ItemsRemove_Button.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.ItemsRemove_Button.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.ItemsRemove_Button.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.ItemsRemove_Button.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.ItemsRemove_Button.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.ItemsRemove_Button.IconMarginLeft = 11;
            this.ItemsRemove_Button.IconPadding = 10;
            this.ItemsRemove_Button.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.ItemsRemove_Button.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.ItemsRemove_Button.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.ItemsRemove_Button.IconSize = 25;
            this.ItemsRemove_Button.IdleBorderColor = System.Drawing.Color.Silver;
            this.ItemsRemove_Button.IdleBorderRadius = 1;
            this.ItemsRemove_Button.IdleBorderThickness = 1;
            this.ItemsRemove_Button.IdleFillColor = System.Drawing.Color.Silver;
            this.ItemsRemove_Button.IdleIconLeftImage = null;
            this.ItemsRemove_Button.IdleIconRightImage = null;
            this.ItemsRemove_Button.IndicateFocus = false;
            this.ItemsRemove_Button.Location = new System.Drawing.Point(12, 104);
            this.ItemsRemove_Button.Name = "ItemsRemove_Button";
            this.ItemsRemove_Button.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.ItemsRemove_Button.OnDisabledState.BorderRadius = 1;
            this.ItemsRemove_Button.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ItemsRemove_Button.OnDisabledState.BorderThickness = 1;
            this.ItemsRemove_Button.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ItemsRemove_Button.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.ItemsRemove_Button.OnDisabledState.IconLeftImage = null;
            this.ItemsRemove_Button.OnDisabledState.IconRightImage = null;
            this.ItemsRemove_Button.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.ItemsRemove_Button.onHoverState.BorderRadius = 1;
            this.ItemsRemove_Button.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ItemsRemove_Button.onHoverState.BorderThickness = 1;
            this.ItemsRemove_Button.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.ItemsRemove_Button.onHoverState.ForeColor = System.Drawing.Color.White;
            this.ItemsRemove_Button.onHoverState.IconLeftImage = null;
            this.ItemsRemove_Button.onHoverState.IconRightImage = null;
            this.ItemsRemove_Button.OnIdleState.BorderColor = System.Drawing.Color.Silver;
            this.ItemsRemove_Button.OnIdleState.BorderRadius = 1;
            this.ItemsRemove_Button.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ItemsRemove_Button.OnIdleState.BorderThickness = 1;
            this.ItemsRemove_Button.OnIdleState.FillColor = System.Drawing.Color.Silver;
            this.ItemsRemove_Button.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.ItemsRemove_Button.OnIdleState.IconLeftImage = null;
            this.ItemsRemove_Button.OnIdleState.IconRightImage = null;
            this.ItemsRemove_Button.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.ItemsRemove_Button.OnPressedState.BorderRadius = 1;
            this.ItemsRemove_Button.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ItemsRemove_Button.OnPressedState.BorderThickness = 1;
            this.ItemsRemove_Button.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.ItemsRemove_Button.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.ItemsRemove_Button.OnPressedState.IconLeftImage = null;
            this.ItemsRemove_Button.OnPressedState.IconRightImage = null;
            this.ItemsRemove_Button.Size = new System.Drawing.Size(400, 37);
            this.ItemsRemove_Button.TabIndex = 11;
            this.ItemsRemove_Button.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.ItemsRemove_Button.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.ItemsRemove_Button.TextMarginLeft = 0;
            this.ItemsRemove_Button.TextPadding = new System.Windows.Forms.Padding(0);
            this.ItemsRemove_Button.UseDefaultRadiusAndThickness = true;
            this.ItemsRemove_Button.Click += new System.EventHandler(this.ItemsRemove_Button_Click);
            // 
            // LinksRemove_Button
            // 
            this.LinksRemove_Button.AllowAnimations = true;
            this.LinksRemove_Button.AllowMouseEffects = true;
            this.LinksRemove_Button.AllowToggling = false;
            this.LinksRemove_Button.AnimationSpeed = 200;
            this.LinksRemove_Button.AutoGenerateColors = false;
            this.LinksRemove_Button.AutoRoundBorders = false;
            this.LinksRemove_Button.AutoSizeLeftIcon = true;
            this.LinksRemove_Button.AutoSizeRightIcon = true;
            this.LinksRemove_Button.BackColor = System.Drawing.Color.Transparent;
            this.LinksRemove_Button.BackColor1 = System.Drawing.Color.Silver;
            this.LinksRemove_Button.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("LinksRemove_Button.BackgroundImage")));
            this.LinksRemove_Button.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.LinksRemove_Button.ButtonText = "Remove selected";
            this.LinksRemove_Button.ButtonTextMarginLeft = 0;
            this.LinksRemove_Button.ColorContrastOnClick = 45;
            this.LinksRemove_Button.ColorContrastOnHover = 45;
            this.LinksRemove_Button.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.LinksRemove_Button.CustomizableEdges = borderEdges4;
            this.LinksRemove_Button.DialogResult = System.Windows.Forms.DialogResult.None;
            this.LinksRemove_Button.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.LinksRemove_Button.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.LinksRemove_Button.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.LinksRemove_Button.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.LinksRemove_Button.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.LinksRemove_Button.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.LinksRemove_Button.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.LinksRemove_Button.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.LinksRemove_Button.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.LinksRemove_Button.IconMarginLeft = 11;
            this.LinksRemove_Button.IconPadding = 10;
            this.LinksRemove_Button.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.LinksRemove_Button.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.LinksRemove_Button.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.LinksRemove_Button.IconSize = 25;
            this.LinksRemove_Button.IdleBorderColor = System.Drawing.Color.Silver;
            this.LinksRemove_Button.IdleBorderRadius = 1;
            this.LinksRemove_Button.IdleBorderThickness = 1;
            this.LinksRemove_Button.IdleFillColor = System.Drawing.Color.Silver;
            this.LinksRemove_Button.IdleIconLeftImage = null;
            this.LinksRemove_Button.IdleIconRightImage = null;
            this.LinksRemove_Button.IndicateFocus = false;
            this.LinksRemove_Button.Location = new System.Drawing.Point(438, 104);
            this.LinksRemove_Button.Name = "LinksRemove_Button";
            this.LinksRemove_Button.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.LinksRemove_Button.OnDisabledState.BorderRadius = 1;
            this.LinksRemove_Button.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.LinksRemove_Button.OnDisabledState.BorderThickness = 1;
            this.LinksRemove_Button.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.LinksRemove_Button.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.LinksRemove_Button.OnDisabledState.IconLeftImage = null;
            this.LinksRemove_Button.OnDisabledState.IconRightImage = null;
            this.LinksRemove_Button.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.LinksRemove_Button.onHoverState.BorderRadius = 1;
            this.LinksRemove_Button.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.LinksRemove_Button.onHoverState.BorderThickness = 1;
            this.LinksRemove_Button.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.LinksRemove_Button.onHoverState.ForeColor = System.Drawing.Color.White;
            this.LinksRemove_Button.onHoverState.IconLeftImage = null;
            this.LinksRemove_Button.onHoverState.IconRightImage = null;
            this.LinksRemove_Button.OnIdleState.BorderColor = System.Drawing.Color.Silver;
            this.LinksRemove_Button.OnIdleState.BorderRadius = 1;
            this.LinksRemove_Button.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.LinksRemove_Button.OnIdleState.BorderThickness = 1;
            this.LinksRemove_Button.OnIdleState.FillColor = System.Drawing.Color.Silver;
            this.LinksRemove_Button.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.LinksRemove_Button.OnIdleState.IconLeftImage = null;
            this.LinksRemove_Button.OnIdleState.IconRightImage = null;
            this.LinksRemove_Button.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.LinksRemove_Button.OnPressedState.BorderRadius = 1;
            this.LinksRemove_Button.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.LinksRemove_Button.OnPressedState.BorderThickness = 1;
            this.LinksRemove_Button.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.LinksRemove_Button.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.LinksRemove_Button.OnPressedState.IconLeftImage = null;
            this.LinksRemove_Button.OnPressedState.IconRightImage = null;
            this.LinksRemove_Button.Size = new System.Drawing.Size(400, 37);
            this.LinksRemove_Button.TabIndex = 12;
            this.LinksRemove_Button.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.LinksRemove_Button.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.LinksRemove_Button.TextMarginLeft = 0;
            this.LinksRemove_Button.TextPadding = new System.Windows.Forms.Padding(0);
            this.LinksRemove_Button.UseDefaultRadiusAndThickness = true;
            this.LinksRemove_Button.Click += new System.EventHandler(this.LinksRemove_Button_Click);
            // 
            // LinksClear_Button
            // 
            this.LinksClear_Button.AllowAnimations = true;
            this.LinksClear_Button.AllowMouseEffects = true;
            this.LinksClear_Button.AllowToggling = false;
            this.LinksClear_Button.AnimationSpeed = 200;
            this.LinksClear_Button.AutoGenerateColors = false;
            this.LinksClear_Button.AutoRoundBorders = false;
            this.LinksClear_Button.AutoSizeLeftIcon = true;
            this.LinksClear_Button.AutoSizeRightIcon = true;
            this.LinksClear_Button.BackColor = System.Drawing.Color.Transparent;
            this.LinksClear_Button.BackColor1 = System.Drawing.Color.Silver;
            this.LinksClear_Button.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("LinksClear_Button.BackgroundImage")));
            this.LinksClear_Button.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.LinksClear_Button.ButtonText = "Clear selected";
            this.LinksClear_Button.ButtonTextMarginLeft = 0;
            this.LinksClear_Button.ColorContrastOnClick = 45;
            this.LinksClear_Button.ColorContrastOnHover = 45;
            this.LinksClear_Button.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.LinksClear_Button.CustomizableEdges = borderEdges5;
            this.LinksClear_Button.DialogResult = System.Windows.Forms.DialogResult.None;
            this.LinksClear_Button.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.LinksClear_Button.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.LinksClear_Button.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.LinksClear_Button.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.LinksClear_Button.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.LinksClear_Button.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.LinksClear_Button.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.LinksClear_Button.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.LinksClear_Button.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.LinksClear_Button.IconMarginLeft = 11;
            this.LinksClear_Button.IconPadding = 10;
            this.LinksClear_Button.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.LinksClear_Button.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.LinksClear_Button.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.LinksClear_Button.IconSize = 25;
            this.LinksClear_Button.IdleBorderColor = System.Drawing.Color.Silver;
            this.LinksClear_Button.IdleBorderRadius = 1;
            this.LinksClear_Button.IdleBorderThickness = 1;
            this.LinksClear_Button.IdleFillColor = System.Drawing.Color.Silver;
            this.LinksClear_Button.IdleIconLeftImage = null;
            this.LinksClear_Button.IdleIconRightImage = null;
            this.LinksClear_Button.IndicateFocus = false;
            this.LinksClear_Button.Location = new System.Drawing.Point(438, 147);
            this.LinksClear_Button.Name = "LinksClear_Button";
            this.LinksClear_Button.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.LinksClear_Button.OnDisabledState.BorderRadius = 1;
            this.LinksClear_Button.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.LinksClear_Button.OnDisabledState.BorderThickness = 1;
            this.LinksClear_Button.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.LinksClear_Button.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.LinksClear_Button.OnDisabledState.IconLeftImage = null;
            this.LinksClear_Button.OnDisabledState.IconRightImage = null;
            this.LinksClear_Button.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.LinksClear_Button.onHoverState.BorderRadius = 1;
            this.LinksClear_Button.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.LinksClear_Button.onHoverState.BorderThickness = 1;
            this.LinksClear_Button.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.LinksClear_Button.onHoverState.ForeColor = System.Drawing.Color.White;
            this.LinksClear_Button.onHoverState.IconLeftImage = null;
            this.LinksClear_Button.onHoverState.IconRightImage = null;
            this.LinksClear_Button.OnIdleState.BorderColor = System.Drawing.Color.Silver;
            this.LinksClear_Button.OnIdleState.BorderRadius = 1;
            this.LinksClear_Button.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.LinksClear_Button.OnIdleState.BorderThickness = 1;
            this.LinksClear_Button.OnIdleState.FillColor = System.Drawing.Color.Silver;
            this.LinksClear_Button.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.LinksClear_Button.OnIdleState.IconLeftImage = null;
            this.LinksClear_Button.OnIdleState.IconRightImage = null;
            this.LinksClear_Button.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.LinksClear_Button.OnPressedState.BorderRadius = 1;
            this.LinksClear_Button.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.LinksClear_Button.OnPressedState.BorderThickness = 1;
            this.LinksClear_Button.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.LinksClear_Button.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.LinksClear_Button.OnPressedState.IconLeftImage = null;
            this.LinksClear_Button.OnPressedState.IconRightImage = null;
            this.LinksClear_Button.Size = new System.Drawing.Size(400, 37);
            this.LinksClear_Button.TabIndex = 13;
            this.LinksClear_Button.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.LinksClear_Button.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.LinksClear_Button.TextMarginLeft = 0;
            this.LinksClear_Button.TextPadding = new System.Windows.Forms.Padding(0);
            this.LinksClear_Button.UseDefaultRadiusAndThickness = true;
            this.LinksClear_Button.Click += new System.EventHandler(this.LinksClear_Button_Click);
            // 
            // ItemsClear_Button
            // 
            this.ItemsClear_Button.AllowAnimations = true;
            this.ItemsClear_Button.AllowMouseEffects = true;
            this.ItemsClear_Button.AllowToggling = false;
            this.ItemsClear_Button.AnimationSpeed = 200;
            this.ItemsClear_Button.AutoGenerateColors = false;
            this.ItemsClear_Button.AutoRoundBorders = false;
            this.ItemsClear_Button.AutoSizeLeftIcon = true;
            this.ItemsClear_Button.AutoSizeRightIcon = true;
            this.ItemsClear_Button.BackColor = System.Drawing.Color.Transparent;
            this.ItemsClear_Button.BackColor1 = System.Drawing.Color.Silver;
            this.ItemsClear_Button.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ItemsClear_Button.BackgroundImage")));
            this.ItemsClear_Button.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ItemsClear_Button.ButtonText = "Clear selected";
            this.ItemsClear_Button.ButtonTextMarginLeft = 0;
            this.ItemsClear_Button.ColorContrastOnClick = 45;
            this.ItemsClear_Button.ColorContrastOnHover = 45;
            this.ItemsClear_Button.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.ItemsClear_Button.CustomizableEdges = borderEdges6;
            this.ItemsClear_Button.DialogResult = System.Windows.Forms.DialogResult.None;
            this.ItemsClear_Button.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.ItemsClear_Button.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ItemsClear_Button.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.ItemsClear_Button.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.ItemsClear_Button.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.ItemsClear_Button.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.ItemsClear_Button.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.ItemsClear_Button.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.ItemsClear_Button.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.ItemsClear_Button.IconMarginLeft = 11;
            this.ItemsClear_Button.IconPadding = 10;
            this.ItemsClear_Button.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.ItemsClear_Button.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.ItemsClear_Button.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.ItemsClear_Button.IconSize = 25;
            this.ItemsClear_Button.IdleBorderColor = System.Drawing.Color.Silver;
            this.ItemsClear_Button.IdleBorderRadius = 1;
            this.ItemsClear_Button.IdleBorderThickness = 1;
            this.ItemsClear_Button.IdleFillColor = System.Drawing.Color.Silver;
            this.ItemsClear_Button.IdleIconLeftImage = null;
            this.ItemsClear_Button.IdleIconRightImage = null;
            this.ItemsClear_Button.IndicateFocus = false;
            this.ItemsClear_Button.Location = new System.Drawing.Point(12, 147);
            this.ItemsClear_Button.Name = "ItemsClear_Button";
            this.ItemsClear_Button.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.ItemsClear_Button.OnDisabledState.BorderRadius = 1;
            this.ItemsClear_Button.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ItemsClear_Button.OnDisabledState.BorderThickness = 1;
            this.ItemsClear_Button.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ItemsClear_Button.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.ItemsClear_Button.OnDisabledState.IconLeftImage = null;
            this.ItemsClear_Button.OnDisabledState.IconRightImage = null;
            this.ItemsClear_Button.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.ItemsClear_Button.onHoverState.BorderRadius = 1;
            this.ItemsClear_Button.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ItemsClear_Button.onHoverState.BorderThickness = 1;
            this.ItemsClear_Button.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.ItemsClear_Button.onHoverState.ForeColor = System.Drawing.Color.White;
            this.ItemsClear_Button.onHoverState.IconLeftImage = null;
            this.ItemsClear_Button.onHoverState.IconRightImage = null;
            this.ItemsClear_Button.OnIdleState.BorderColor = System.Drawing.Color.Silver;
            this.ItemsClear_Button.OnIdleState.BorderRadius = 1;
            this.ItemsClear_Button.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ItemsClear_Button.OnIdleState.BorderThickness = 1;
            this.ItemsClear_Button.OnIdleState.FillColor = System.Drawing.Color.Silver;
            this.ItemsClear_Button.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.ItemsClear_Button.OnIdleState.IconLeftImage = null;
            this.ItemsClear_Button.OnIdleState.IconRightImage = null;
            this.ItemsClear_Button.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.ItemsClear_Button.OnPressedState.BorderRadius = 1;
            this.ItemsClear_Button.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ItemsClear_Button.OnPressedState.BorderThickness = 1;
            this.ItemsClear_Button.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.ItemsClear_Button.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.ItemsClear_Button.OnPressedState.IconLeftImage = null;
            this.ItemsClear_Button.OnPressedState.IconRightImage = null;
            this.ItemsClear_Button.Size = new System.Drawing.Size(400, 37);
            this.ItemsClear_Button.TabIndex = 14;
            this.ItemsClear_Button.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.ItemsClear_Button.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.ItemsClear_Button.TextMarginLeft = 0;
            this.ItemsClear_Button.TextPadding = new System.Windows.Forms.Padding(0);
            this.ItemsClear_Button.UseDefaultRadiusAndThickness = true;
            this.ItemsClear_Button.Click += new System.EventHandler(this.ItemsClear_Button_Click);
            // 
            // MainWindow
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.SystemColors.Control;
            this.ClientSize = new System.Drawing.Size(852, 689);
            this.Controls.Add(this.ItemsClear_Button);
            this.Controls.Add(this.LinksClear_Button);
            this.Controls.Add(this.LinksRemove_Button);
            this.Controls.Add(this.ItemsRemove_Button);
            this.Controls.Add(this.AddItem_Button);
            this.Controls.Add(this.AddLink_Button);
            this.Controls.Add(this.Link_TextBox);
            this.Controls.Add(this.Item_TextBox);
            this.Controls.Add(this.Links_ListBox);
            this.Controls.Add(this.Items_ListBox);
            this.Controls.Add(this.bunifuSeparator3);
            this.Controls.Add(this.bunifuSeparator2);
            this.Controls.Add(this.Links_label);
            this.Controls.Add(this.Items_label);
            this.Controls.Add(this.bunifuSeparator1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.MaximizeBox = false;
            this.Name = "MainWindow";
            this.Text = "GlumSak paste creator";
            this.Load += new System.EventHandler(this.MainWindow_Load);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuSeparator bunifuSeparator1;
        private Bunifu.UI.WinForms.BunifuLabel Items_label;
        private Bunifu.UI.WinForms.BunifuLabel Links_label;
        private Bunifu.UI.WinForms.BunifuSeparator bunifuSeparator2;
        private Bunifu.UI.WinForms.BunifuSeparator bunifuSeparator3;
        private System.Windows.Forms.ListBox Items_ListBox;
        private System.Windows.Forms.ListBox Links_ListBox;
        private Bunifu.UI.WinForms.BunifuTextBox Item_TextBox;
        private Bunifu.UI.WinForms.BunifuTextBox Link_TextBox;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AddLink_Button;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AddItem_Button;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton ItemsRemove_Button;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton LinksRemove_Button;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton LinksClear_Button;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton ItemsClear_Button;
    }
}

